/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReportMenuOption.java
 *
 * Created on 01-Nov-2013, 15:01:55
 */
package inventory.system.ui;

/**
 *
 * @author User
 */
public class ReportMenuOption extends javax.swing.JPanel {

    /** Creates new form ReportMenuOption */
    public ReportMenuOption() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(inventory.system.ui.ShoesShopApp.class).getContext().getResourceMap(ReportMenuOption.class);
        setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setFont(resourceMap.getFont("lblReportOption.font")); // NOI18N
        jLabel1.setText(resourceMap.getString("lblReportOption.text")); // NOI18N
        jLabel1.setName("lblReportOption"); // NOI18N

        jButton1.setText(resourceMap.getString("btnCalculateProfits.text")); // NOI18N
        jButton1.setName("btnCalculateProfits"); // NOI18N

        jLabel2.setText(resourceMap.getString("lblMonthDetails.text")); // NOI18N
        jLabel2.setName("lblMonthDetails"); // NOI18N

        jTextField1.setText(resourceMap.getString("txtMonthDetails.text")); // NOI18N
        jTextField1.setName("txtMonthDetails"); // NOI18N

        jButton2.setText(resourceMap.getString("btnNoProductSold.text")); // NOI18N
        jButton2.setActionCommand(resourceMap.getString("btnNoProductSold.actionCommand")); // NOI18N
        jButton2.setName("btnNoProductSold"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                        .addGap(227, 227, 227))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(179, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jButton1)
                .addGap(26, 26, 26)
                .addComponent(jButton2)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName(resourceMap.getString("lblReportOption.AccessibleContext.accessibleName")); // NOI18N
        jButton1.getAccessibleContext().setAccessibleName(resourceMap.getString("btnCalculateProfits.AccessibleContext.accessibleName")); // NOI18N
        jLabel2.getAccessibleContext().setAccessibleName(resourceMap.getString("lblMonthDetails.AccessibleContext.accessibleName")); // NOI18N
        jTextField1.getAccessibleContext().setAccessibleName(resourceMap.getString("txtMonthDetails.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
